server:
  port: 8080

spring:
  application:
    name: zelda-plateform-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: zelda-plateform-uaa
          uri: lb://zelda-plateform-uaa
          predicates:
            - Path=/oauth/**,/login/**,/actuator/**
          filters:
            - StripPrefix=0
        - id: zelda-demo-app
          uri: lb://zelda-demo-app
          predicates:
            - Path=/orders/**,/demo/**
          filters:
            - StripPrefix=0
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0

# Sa-Token 配置
sa-token:
  token-name: Authorization
  timeout: 86400
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false
  is-print: false

cloud:
  nacos:
    discovery:
      server-addr: localhost:8848
      namespace: public
      group: DEFAULT_GROUP
    config:
      server-addr: localhost:8848
      namespace: public
      group: DEFAULT_GROUP
      file-extension: yaml
      refresh-enabled: true

logging:
  level:
    com.blue.zelda.platform.gateway: debug
    cn.dev33.satoken: info
